version: '3.8'
services:
    frontend:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - '.:/app/frontend'
            - '/app/frontend/node_modules'
