# Generated by Django 3.1.3 on 2020-11-21 21:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to=users.models.upload_loaction, verbose_name='Image'),
        ),
    ]
